version: '3.8'

services:
  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "/bin/sh", "-c" ]
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ./main